name: Security audit - on push

on:
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
    tags-ignore:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/audit@v1
